name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-setup:
    name: Setup test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      DEBUG: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: stable
      - name: Test success
        uses: ./
        with:
          path: testdata/check_success
      - name: Test failure
        id: test-failure
        uses: ./
        with:
          path: testdata/check_failure
          force-setup: true
        continue-on-error: true
      - name: Check failure
        shell: bash
        run: |
          if [[ "${{ steps.test-failure.outputs.exitcode }}" != "1" ]]; then
            echo "Expected exit code 1, but got ${{ steps.test-failure.outputs.exitcode }}"
            exit 1
          fi
      - name: Run gocredits
        run: gocredits -version
